apiVersion: v2
name: prometheus
description: A Helm chart for Prometheus
type: application
version: 47.2.0
dependencies:
- name: kube-prometheus-stack
  version: "22.7.0"
  repository: "https://prometheus-community.github.io/helm-charts"
