apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: test-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./applications/test-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
