apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
  annotations:
    fluxcd.io/ignore: "false"
spec:
  interval: 1m0s
  chart:
    spec:
      chart: prometheus
      version: '22.6.6'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    serviceMonitors:
    - name: flux-metrics
      selector:
        matchLabels:
          app.kubernetes.io/name: flux
      namespaceSelector:
        matchNames:
        - flux
      endpoints:
      - port: metrics
        interval: 30s