apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux
  namespace: flux-system
spec:
  podMetricsEndpoints:
  - interval: 10s
    port: http-metrics
  selector:
    matchLabels:
      app: flux