apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: flux-metrics
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      name: flux  # Adjust this to match the label of the Flux CD service
  endpoints:
  - port: http
    path: /metrics
