apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tiberiucozan/diploma-project.git
    targetRevision: HEAD
    path: argo/prometheus/
    helm:
      values: | 
        serviceMonitors:
        - name: argocd
          selector:
            matchLabels:
              app.kubernetes.io/name: argocd-metrics
          namespaceSelector:
            matchNames:
            - argocd
          endpoints:
          - port: metrics
            interval: 30s
        service:
          type: LoadBalancer
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true