name: 'Terraform'

on:
  push:
    paths:
    - 'terraform/**'
    branches:
    - main
  pull_request:
    paths:
    - 'terraform/**'

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Plan
      run: terraform plan -var="civo_token=${{ secrets.CIVO_TOKEN }}"
      working-directory: terraform

  apply:
    name: 'Terraform Apply'
    needs: terraform
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve -var="civo_token=${{ secrets.CIVO_TOKEN }}"
      working-directory: terraform
