name: Update branches

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target Branch'     
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Git
        run: |
          git config user.name "${{ secrets.USERNAME }}"
          git config user.email "${{ secrets.USERNAME }}@users.noreply.github.com"

      - name: Update branch
        run: |
          git fetch origin
          git checkout ${{ github.event.inputs.target_branch }}
          git merge origin/main
          git push origin ${{ github.event.inputs.target_branch }}
